# Generated by Django 6.0.1 on 2026-01-23 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, choices=[('', 'Select Gender'), ('male', 'Male'), ('female', 'Female')], default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'No Gender'), ('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
    ]
