# Generated by Django 6.0.1 on 2026-01-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_gender_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'No Gender'), ('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='', max_length=10),
        ),
    ]
