# Generated by Django 6.0.1 on 2026-01-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_gender_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'No Gender'), ('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], max_length=10, null=True),
        ),
    ]
