# Generated by Django 6.0.1 on 2026-01-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'gender'], name='products_pr_categor_3c67d4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['description'], name='products_pr_descrip_993c49_idx'),
        ),
    ]
