# Generated by Django 6.0.1 on 2026-01-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_products_pr_categor_3c67d4_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
